In [1]:
import music21
from collections import Counter
import numpy as np
import glob

In [2]:
#for listing down the file names
import os

#Array Processing
import numpy as np

#specify the path
path="dataset"
files = [a for a in glob.glob("dataset/*/*")]

In [3]:
len(files)

295

In [36]:
# Load the MIDI file
scores =[]
for i, file in enumerate(files[150:200]):
    print(i, file)
    try:
        scores.append(music21.converter.parse(file))
        print(f'{i} appended')
    except:
        print(f'{i} error')
        continue
len(scores)

0 dataset\haydn\haydn_33_2.mid


C:\Users\sajjan\anaconda3\envs\tf\lib\site-packages\music21\midi\translate.py:863: TranslateWarning: Unable to determine instrument from <music21.midi.MidiEvent SEQUENCE_TRACK_NAME, track=5, channel=None, data=b'Copyright \xa9 2010 by Bernd Krueger'>; getting generic Instrument
  warnings.warn(


0 appended
1 dataset\haydn\haydn_33_3.mid
1 appended
2 dataset\haydn\haydn_35_1.mid
2 appended
3 dataset\haydn\haydn_35_2.mid
3 appended
4 dataset\haydn\haydn_35_3.mid
4 appended
5 dataset\haydn\haydn_43_1.mid
5 appended
6 dataset\haydn\haydn_43_2.mid
6 appended
7 dataset\haydn\haydn_43_3.mid
7 appended
8 dataset\haydn\haydn_7_1.mid
8 appended
9 dataset\haydn\haydn_7_2.mid
9 appended
10 dataset\haydn\haydn_7_3.mid
10 appended
11 dataset\haydn\haydn_8_1.mid
11 appended
12 dataset\haydn\haydn_8_2.mid
12 appended
13 dataset\haydn\haydn_8_3.mid
13 appended
14 dataset\haydn\haydn_8_4.mid
14 appended
15 dataset\haydn\haydn_9_1.mid
15 appended
16 dataset\haydn\haydn_9_2.mid
16 appended
17 dataset\haydn\haydn_9_3.mid
17 appended
18 dataset\haydn\hay_40_1.mid


C:\Users\sajjan\anaconda3\envs\tf\lib\site-packages\music21\midi\translate.py:863: TranslateWarning: Unable to determine instrument from <music21.midi.MidiEvent SEQUENCE_TRACK_NAME, track=5, channel=None, data=b'Copyright \xa9 1998 by Bernd Kr\xfcger'>; getting generic Instrument
  warnings.warn(


18 appended
19 dataset\haydn\hay_40_2.mid
19 appended
20 dataset\liszt\liz_donjuan.mid


C:\Users\sajjan\anaconda3\envs\tf\lib\site-packages\music21\midi\translate.py:863: TranslateWarning: Unable to determine instrument from <music21.midi.MidiEvent SEQUENCE_TRACK_NAME, track=6, channel=None, data=b'Copyright \xa9 2004 by Bernd Kr\xfcger'>; getting generic Instrument
  warnings.warn(


20 appended
21 dataset\liszt\liz_et1.mid
21 appended
22 dataset\liszt\liz_et2.mid


C:\Users\sajjan\anaconda3\envs\tf\lib\site-packages\music21\midi\translate.py:863: TranslateWarning: Unable to determine instrument from <music21.midi.MidiEvent SEQUENCE_TRACK_NAME, track=4, channel=None, data=b'Copyright \xa9 1998 by Bernd Kr\xfcger'>; getting generic Instrument
  warnings.warn(


22 appended
23 dataset\liszt\liz_et3.mid
23 appended
24 dataset\liszt\liz_et4.mid
24 appended
25 dataset\liszt\liz_et5.mid
25 appended
26 dataset\liszt\liz_et6.mid
26 appended
27 dataset\liszt\liz_et_trans4.mid


C:\Users\sajjan\anaconda3\envs\tf\lib\site-packages\music21\midi\translate.py:863: TranslateWarning: Unable to determine instrument from <music21.midi.MidiEvent SEQUENCE_TRACK_NAME, track=5, channel=None, data=b'Copyright \xa9 2006 by Bernd Krueger'>; getting generic Instrument
  warnings.warn(


27 appended
28 dataset\liszt\liz_et_trans5.mid
28 appended
29 dataset\liszt\liz_et_trans8.mid


C:\Users\sajjan\anaconda3\envs\tf\lib\site-packages\music21\midi\translate.py:863: TranslateWarning: Unable to determine instrument from <music21.midi.MidiEvent SEQUENCE_TRACK_NAME, track=5, channel=None, data=b'Copyright \xa9 2007 by Bernd Krueger'>; getting generic Instrument
  warnings.warn(


29 appended
30 dataset\liszt\liz_liebestraum.mid
30 appended
31 dataset\liszt\liz_rhap02.mid
31 appended
32 dataset\liszt\liz_rhap09.mid
32 appended
33 dataset\liszt\liz_rhap10.mid
33 appended
34 dataset\liszt\liz_rhap12.mid
34 appended
35 dataset\liszt\liz_rhap15.mid
35 appended
36 dataset\mendelssohn\mendel_op19_1.mid


C:\Users\sajjan\anaconda3\envs\tf\lib\site-packages\music21\midi\translate.py:863: TranslateWarning: Unable to determine instrument from <music21.midi.MidiEvent SEQUENCE_TRACK_NAME, track=6, channel=None, data=b'Copyright \xa9 2010 by Bernd Krueger'>; getting generic Instrument
  warnings.warn(


36 appended
37 dataset\mendelssohn\mendel_op19_2.mid
37 error
38 dataset\mendelssohn\mendel_op19_3.mid


C:\Users\sajjan\anaconda3\envs\tf\lib\site-packages\music21\midi\translate.py:863: TranslateWarning: Unable to determine instrument from <music21.midi.MidiEvent SEQUENCE_TRACK_NAME, track=0, channel=None, data=b'J\xe4gerlied'>; getting generic Instrument
  warnings.warn(


38 appended
39 dataset\mendelssohn\mendel_op19_4.mid
39 appended
40 dataset\mendelssohn\mendel_op19_5.mid
40 appended
41 dataset\mendelssohn\mendel_op19_6.mid
41 appended
42 dataset\mendelssohn\mendel_op30_1.mid


C:\Users\sajjan\anaconda3\envs\tf\lib\site-packages\music21\midi\translate.py:863: TranslateWarning: Unable to determine instrument from <music21.midi.MidiEvent SEQUENCE_TRACK_NAME, track=5, channel=None, data=b'Copyright \xa9 2000 by Bernd Kr\xfcger'>; getting generic Instrument
  warnings.warn(


42 appended
43 dataset\mendelssohn\mendel_op30_2.mid
43 appended
44 dataset\mendelssohn\mendel_op30_3.mid
44 appended
45 dataset\mendelssohn\mendel_op30_4.mid
45 appended
46 dataset\mendelssohn\mendel_op30_5.mid
46 appended
47 dataset\mendelssohn\mendel_op53_5.mid
47 appended
48 dataset\mendelssohn\mendel_op62_3.mid
48 appended
49 dataset\mendelssohn\mendel_op62_4.mid
49 appended


49

In [37]:
def extract_pitch_sequence(score):

    # Extract the pitch class sequence
    # Initialize an empty list to store the pitch class sequence
    pitch_class_sequence = []


    # Iterate through all elements in the score
    for element in score.flat:
        # Check if the element is a note
        if 'Note' in element.classes:
            pitch_class_sequence.append(element.pitch.pitchClass)
        # Check if the element is a chord
        elif 'Chord' in element.classes:
            for pitch in element.pitches:
                pitch_class_sequence.append(pitch.pitchClass)
    return pitch_class_sequence


In [38]:
pitch_sequences_songs = []
for score in scores:
    pitch_sequences_songs.append(extract_pitch_sequence(score))

In [39]:
len(pitch_sequences_songs[0])

1365

In [40]:
pitch_class_histogram = []
for indv_pitch_sequence in pitch_sequences_songs:

    # Compute the pitch class histogram
    pitch_class_histogram.append(Counter(indv_pitch_sequence))
pitch_class_histogram

[Counter({9: 211,
          5: 193,
          2: 172,
          1: 54,
          7: 191,
          4: 154,
          10: 193,
          8: 17,
          0: 138,
          3: 21,
          11: 4,
          6: 17}),
 Counter({9: 293,
          6: 166,
          2: 344,
          1: 121,
          4: 216,
          7: 244,
          11: 67,
          8: 18,
          5: 130,
          10: 72,
          0: 48,
          3: 16}),
 Counter({0: 519,
          4: 427,
          7: 692,
          11: 407,
          5: 201,
          2: 527,
          9: 287,
          10: 46,
          6: 167,
          1: 45,
          3: 41,
          8: 39}),
 Counter({9: 256,
          0: 472,
          5: 322,
          10: 192,
          7: 350,
          4: 216,
          2: 166,
          1: 16,
          6: 20,
          11: 60,
          8: 2,
          3: 24}),
 Counter({4: 151,
          0: 196,
          7: 314,
          5: 135,
          2: 160,
          11: 124,
          8: 27,
          9: 94

In [41]:
len(pitch_class_histogram[5].values())

12

In [42]:
def padding_counter(values):
    # calculate the amount of padding needed
    pad_width = 12 - len(values)
    if pad_width >0:
        # pad array a with zeros on the left
        padded_pitch_class = np.pad(values, (pad_width, 0), 'constant', constant_values = (0, 0))
    else:
        padded_pitch_class = np.array(values[:12])
    # check the size of the arrays
    #print(len(padded_pitch_class), padded_pitch_class) # prints 8
    return padded_pitch_class

Getting which notes are played the most during the duration of the midi song

In [44]:
padded_class = []
for counter in pitch_class_histogram:
    padded_class.append(padding_counter(list(counter)))
    
len(padded_class), padded_class

(49,
 [array([ 9,  5,  2,  1,  7,  4, 10,  8,  0,  3, 11,  6]),
  array([ 9,  6,  2,  1,  4,  7, 11,  8,  5, 10,  0,  3]),
  array([ 0,  4,  7, 11,  5,  2,  9, 10,  6,  1,  3,  8]),
  array([ 9,  0,  5, 10,  7,  4,  2,  1,  6, 11,  8,  3]),
  array([ 4,  0,  7,  5,  2, 11,  8,  9,  6, 10,  1,  3]),
  array([ 3,  0,  8, 10,  7,  1,  5,  9, 11,  6,  2,  4]),
  array([ 0,  0,  3,  0,  8,  5,  1, 10,  7,  2,  9,  6]),
  array([ 0,  1,  3,  8, 10,  7,  5,  2, 11,  9,  4,  6]),
  array([ 0,  0,  0,  0,  4,  7,  0,  2, 11,  5,  9,  6]),
  array([ 0,  0,  4,  7,  5,  2, 11,  9,  6,  8,  3, 10]),
  array([ 0,  0,  0,  0,  7,  4,  2, 11,  5,  9,  6,  3]),
  array([ 0,  0,  0,  2,  7, 11,  0,  4,  9,  6,  1,  5]),
  array([ 0,  0,  0,  7, 11,  9,  0,  6,  2,  4,  1,  8]),
  array([ 0,  0,  2,  7,  4,  6, 11,  0,  9,  1,  5,  8]),
  array([ 0,  0,  0,  0,  0,  2,  7, 11,  4,  0,  9,  6]),
  array([ 0,  0,  0,  0,  5,  0,  9, 10,  7,  2,  4, 11]),
  array([ 0,  5,  7,  4,  9, 10,  0,  2, 11,  8,  1

reference distributions for all 7 modes obtained by Carol L. Krumhansl and George E. Kessler in their study 

"Tracing the dynamic changes in perceived tonal organization in a spatial representation of musical keys"

In [45]:
# Compute the reference distributions for each mode
ionian_reference = [6.35, 2.23, 3.48, 2.33, 4.38, 4.09, 2.52, 5.19, 2.39, 3.66, 2.29, 2.88]
dorian_reference = [6.33, 2.68, 3.52, 5.38, 2.60, 3.53, 2.54, 4.75, 3.98, 2.69, 3.34, 3.17]
phrygian_reference = [6.31, 2.58, 3.82, 2.92, 3.10, 2.88, 4.89, 2.11, 4.54, 3.93, 2.90, 3.07]
lydian_reference = [6.33, 2.68, 3.52, 5.38, 2.60, 3.53, 2.54, 4.75, 3.98, 2.69, 3.34, 3.17]
mixolydian_reference = [6.33, 2.68, 3.52, 5.38, 2.60, 3.53, 2.54, 4.75, 3.98, 2.69, 3.34, 3.17]
aeolian_reference = [6.33, 2.68, 3.52, 5.38, 2.60, 3.53, 2.54, 4.75, 3.98, 2.69, 3.34, 3.17]
locrian_reference = [6.31, 2.58, 3.82, 2.92, 3.10, 2.88, 4.89, 2.11, 4.54, 3.93, 2.90, 3.07]

In [46]:
def getting_mode(a):

    # Compute the correlation coefficient for each mode
    ionian_similarity = np.corrcoef(a, ionian_reference)[0, 1]
    dorian_similarity = np.corrcoef(a, dorian_reference)[0, 1]
    phrygian_similarity = np.corrcoef(a, phrygian_reference)[0, 1]
    lydian_similarity = np.corrcoef(a, lydian_reference)[0, 1]
    mixolydian_similarity = np.corrcoef(a, mixolydian_reference)[0, 1]
    aeolian_similarity = np.corrcoef(a, aeolian_reference)[0, 1]
    locrian_similarity = np.corrcoef(a, locrian_reference)[0, 1]


    # Find the mode with the highest similarity score
    mode_similarities = [ionian_similarity, dorian_similarity, phrygian_similarity, lydian_similarity, mixolydian_similarity, aeolian_similarity, locrian_similarity]
    mode_index = mode_similarities.index(max(mode_similarities))
    modes = ['Ionian', 'Dorian', 'Phrygian', 'Lydian', 'Mixolydian', 'Aeolian', 'Locrian']
    mode = modes[mode_index]
    return mode

In [47]:
modes = []
for i, arr in enumerate(padded_class):
    modes.append((i, getting_mode(arr)))
    print(modes[-1])

(0, 'Ionian')
(1, 'Phrygian')
(2, 'Dorian')
(3, 'Phrygian')
(4, 'Ionian')
(5, 'Dorian')
(6, 'Ionian')
(7, 'Phrygian')
(8, 'Phrygian')
(9, 'Phrygian')
(10, 'Ionian')
(11, 'Ionian')
(12, 'Ionian')
(13, 'Phrygian')
(14, 'Dorian')
(15, 'Ionian')
(16, 'Ionian')
(17, 'Ionian')
(18, 'Ionian')
(19, 'Phrygian')
(20, 'Dorian')
(21, 'Dorian')
(22, 'Phrygian')
(23, 'Dorian')
(24, 'Ionian')
(25, 'Ionian')
(26, 'Dorian')
(27, 'Ionian')
(28, 'Phrygian')
(29, 'Phrygian')
(30, 'Dorian')
(31, 'Dorian')
(32, 'Dorian')
(33, 'Phrygian')
(34, 'Ionian')
(35, 'Phrygian')
(36, 'Phrygian')
(37, 'Dorian')
(38, 'Ionian')
(39, 'Dorian')
(40, 'Dorian')
(41, 'Phrygian')
(42, 'Dorian')
(43, 'Ionian')
(44, 'Dorian')
(45, 'Phrygian')
(46, 'Dorian')
(47, 'Ionian')
(48, 'Dorian')


In [48]:
unique_modes = list(set([i[1] for i in modes]))

In [49]:
print(unique_modes)

['Ionian', 'Phrygian', 'Dorian']
