In [2]:
import numpy as np
from numpy import math

In [3]:
def positional_encoding(pos, pe):
    for i in range(0, 512, 2):
        pe[0][1] = math.sin(pos /(10000**((2*i)/d_model)))
        po[0][i+1] = math.cos(pos / (10000**((2*i)/d_model)))
    return pe

In [4]:
import matplotlib.pyplot as plt

In [5]:
print("Step 1: Input : 3 inputs, d_model=4")
x =np.array([[1.0, 0.0, 1.0, 0.0], # Input 1
[0.0, 2.0, 0.0, 2.0], # Input 2
[1.0, 1.0, 1.0, 1.0]]) # Input 3
print(x)

Step 1: Input : 3 inputs, d_model=4
[[1. 0. 1. 0.]
 [0. 2. 0. 2.]
 [1. 1. 1. 1.]]


In [6]:
print("Step 2: weights 3 dimensions x d_model=4")
print("w_query")
w_query =np.array([[1, 0, 1],
[1, 0, 0],
[0, 0, 1],
[0, 1, 1]])
print(w_query)

Step 2: weights 3 dimensions x d_model=4
w_query
[[1 0 1]
 [1 0 0]
 [0 0 1]
 [0 1 1]]


In [7]:
print("w_key")
w_key =np.array([[0, 0, 1],
[1, 1, 0],
[0, 1, 0],
[1, 1, 0]])
print(w_key)

w_key
[[0 0 1]
 [1 1 0]
 [0 1 0]
 [1 1 0]]


In [8]:
print("w_value")
w_value = np.array([[0, 2, 0],
[0, 3, 0],
[1, 0, 3],
[1, 1, 0]])
print(w_value)

w_value
[[0 2 0]
 [0 3 0]
 [1 0 3]
 [1 1 0]]


In [11]:

#finding out Q, K, V
#dot product of weights and inputs
Q = np.matmul(x, w_query)
K = np.matmul(x, w_key)
V = np.matmul(x, w_value)
print(f'Q = {Q}')
print(f'K = {K}')
print(f'V = {V}')

Q = [[1. 0. 2.]
 [2. 2. 2.]
 [2. 1. 3.]]
K = [[0. 1. 1.]
 [4. 4. 0.]
 [2. 3. 1.]]
V = [[1. 2. 3.]
 [2. 8. 0.]
 [2. 6. 3.]]


--Scaled Attention Scores

In [19]:
#square root of dim_k = 3 is 1....
# rounded off as 1
sqr_dim_k = 1
attention_scores = (Q @ K.transpose())/sqr_dim_k
print(f'Attention Scores is \n{attention_scores}')

Attention Scores is 
[[ 2.  4.  4.]
 [ 4. 16. 12.]
 [ 4. 12. 10.]]


In [20]:
from scipy.special import softmax

In [21]:
#scaled attention scores for each vector
attention_scores[0] = softmax(attention_scores[0])
attention_scores[1] = softmax(attention_scores[1])
attention_scores[2] = softmax(attention_scores[2])
for i in range(3):
    print(attention_scores[i])

[0.06337894 0.46831053 0.46831053]
[6.03366485e-06 9.82007865e-01 1.79861014e-02]
[2.95387223e-04 8.80536902e-01 1.19167711e-01]


In [26]:
#Values are 
for i in range(3):
    print(V[i])

[1. 2. 3.]
[2. 8. 0.]
[2. 6. 3.]


multiply the intermediate attention score by the 3 'value' vector one by one
to zoom down into the inner workings of the equation

In [32]:
attention1 = attention_scores[0].reshape(-1, 1)
for i in range(3):
    print(attention1[i][0], attention1[i][0].shape)

0.06337893833303763 ()
0.4683105308334813 ()
0.4683105308334813 ()


In [34]:
attention1 = attention_scores[0][0] *V[0]
attention2 = attention_scores[0][1] *V[1]
attention3 = attention_scores[0][2] *V[2]
print(attention1)
print(attention2)
print(attention3)

[0.06337894 0.12675788 0.19013681]
[0.93662106 3.74648425 0.        ]
[0.93662106 2.80986319 1.40493159]


First line of the output values is the summation of 3 attention values

In [36]:
attention_input1 = attention1+attention2+attention3
print(f'First line of the output matrix is {attention_input1}')

First line of the output matrix is [1.93662106 6.68310531 1.59506841]


The second line will be for the output of the next input, i.e. input#2

Assuming random values for actual transformer original paper
3 results of 64 dimensions each

In [37]:
attention_head1 = np.random.random((3, 64))
print(attention_head1)

[[0.13373558 0.45790048 0.46243729 0.65822786 0.65960876 0.88452703
  0.21171315 0.49923099 0.88647875 0.74942882 0.10166282 0.86643135
  0.4000206  0.41588531 0.77027543 0.17391372 0.02864358 0.39789917
  0.65566045 0.31968175 0.01715376 0.09230079 0.29778234 0.37813256
  0.3480465  0.82773456 0.52386483 0.76657683 0.74222086 0.49702274
  0.80666593 0.86689761 0.0079738  0.67573289 0.46455662 0.68468096
  0.75690464 0.91015455 0.94766774 0.05978977 0.11233983 0.86417557
  0.73286392 0.5383743  0.56802435 0.55843749 0.85841064 0.90572334
  0.65563309 0.17282511 0.51676716 0.28526579 0.10489826 0.28224468
  0.55616871 0.97049942 0.93734353 0.88992808 0.29995462 0.97489398
  0.82127739 0.06546661 0.02773831 0.18601905]
 [0.02718355 0.4519143  0.93245817 0.62030322 0.26944405 0.09971777
  0.14503153 0.37790984 0.54681393 0.76235591 0.43374949 0.85029703
  0.20554719 0.05381368 0.86146385 0.23380015 0.35401261 0.26974306
  0.26248555 0.58481752 0.08363527 0.72314849 0.99177062 0.59082474
 

Assumption of 8 heads of the attention sub-layer 
so 3 input vectors has 3 output vectors of d_model=64

In [41]:
print("Trained heads of the attention layer are:")
z0h1=np.random.random((3, 64))
z1h2=np.random.random((3, 64))
z2h3=np.random.random((3, 64))
z3h4=np.random.random((3, 64))
z4h5=np.random.random((3, 64))
z5h6=np.random.random((3, 64))
z6h7=np.random.random((3, 64))
z7h8=np.random.random((3, 64))
print("shape of one head",z0h1.shape,"dimension of 8 heads",64*8)

Trained heads of the attention layer are:
shape of one head (3, 64) dimension of 8 heads 512


Concatenation of the output of the heads

In [43]:
output_attention = np.hstack((z0h1, z1h2, z2h3, z3h4, z4h5, z5h6, z6h7, z7h8))
print(output_attention, output_attention.shape)

[[0.73002511 0.3502825  0.70160739 ... 0.59884761 0.33574044 0.39792195]
 [0.20490409 0.32669716 0.53695721 ... 0.13376205 0.94136011 0.90947728]
 [0.20792747 0.91936149 0.47502873 ... 0.61196262 0.67103404 0.99593312]] (3, 512)


POST-LAYER NORMALIZATION
LayerNorm(x+Sublayer(x))